const toolbarMenuItemsHome = [
  {
    id: "1",
    title: "All Transactions",
    icon: "monetization-on",
  },
  {
    id: "2",
    title: "My Account",
    icon: "account-circle",
  },
  {
    id: "3",
    title: "Logout",
    icon: "logout",
  },
];

const searchBarMenuItemsHome = [
  {
    id: "1",
    title: "All Customers",
    icon: "people",
  },
  {
    id: "2",
    title: "Newly Added",
    icon: "group-add",
  },
  {
    id: "3",
    title: "Payment Due",
    icon: "money-off",
  },
  {
    id: "4",
    title: "Payment in Advance",
    icon: "attach-money",
  },
];

const searchbarMenuItemsContacts = [
  {
    id: "1",
    title: "Ascending Order",
    icon: "",
  },

  {
    id: "2",
    title: "Descending Order",
    icon: "",
  },
];

const countryCodesMenuItems = [
  {id: "0", title: "Options", dial_code: "-", code: "OT"},
  {id: "1", title: "Afghanistan", dial_code: "+93", code: "AF"},
  {id: "2", title: "Aland Islands", dial_code: "+358", code: "AX"},
  {id: "3", title: "Albania", dial_code: "+355", code: "AL"},
  {id: "4", title: "Algeria", dial_code: "+213", code: "DZ"},
  {id: "5", title: "AmericanSamoa", dial_code: "+1684", code: "AS"},
  {id: "6", title: "Andorra", dial_code: "+376", code: "AD"},
  {id: "7", title: "Angola", dial_code: "+244", code: "AO"},
  {id: "8", title: "Anguilla", dial_code: "+1264", code: "AI"},
  {id: "9", title: "Antarctica", dial_code: "+672", code: "AQ"},
  {id: "10", title: "Antigua and Barbuda", dial_code: "+1268", code: "AG"},
  {id: "11", title: "Argentina", dial_code: "+54", code: "AR"},
  {id: "12", title: "Armenia", dial_code: "+374", code: "AM"},
  {id: "13", title: "Aruba", dial_code: "+297", code: "AW"},
  {id: "14", title: "Australia", dial_code: "+61", code: "AU"},
  {id: "15", title: "Austria", dial_code: "+43", code: "AT"},
  {id: "16", title: "Azerbaijan", dial_code: "+994", code: "AZ"},
  {id: "17", title: "Bahamas", dial_code: "+1242", code: "BS"},
  {id: "18", title: "Bahrain", dial_code: "+973", code: "BH"},
  {id: "19", title: "Bangladesh", dial_code: "+880", code: "BD"},
  {id: "20", title: "Barbados", dial_code: "+1246", code: "BB"},
  {id: "21", title: "Belarus", dial_code: "+375", code: "BY"},
  {id: "22", title: "Belgium", dial_code: "+32", code: "BE"},
  {id: "23", title: "Belize", dial_code: "+501", code: "BZ"},
  {id: "24", title: "Benin", dial_code: "+229", code: "BJ"},
  {id: "25", title: "Bermuda", dial_code: "+1441", code: "BM"},
  {id: "26", title: "Bhutan", dial_code: "+975", code: "BT"},
  {id: "27", title: "Bolivia, Plurinational State of", dial_code: "+591", code: "BO"},
  {id: "28", title: "Bosnia and Herzegovina", dial_code: "+387", code: "BA"},
  {id: "29", title: "Botswana", dial_code: "+267", code: "BW"},
  {id: "30", title: "Brazil", dial_code: "+55", code: "BR"},
  {id: "31", title: "British Indian Ocean Territory", dial_code: "+246", code: "IO"},
  {id: "32", title: "Brunei Darussalam", dial_code: "+673", code: "BN"},
  {id: "33", title: "Bulgaria", dial_code: "+359", code: "BG"},
  {id: "34", title: "Burkina Faso", dial_code: "+226", code: "BF"},
  {id: "35", title: "Burundi", dial_code: "+257", code: "BI"},
  {id: "36", title: "Cambodia", dial_code: "+855", code: "KH"},
  {id: "37", title: "Cameroon", dial_code: "+237", code: "CM"},
  {id: "38", title: "Canada", dial_code: "+1", code: "CA"},
  {id: "39", title: "Cape Verde", dial_code: "+238", code: "CV"},
  {id: "40", title: "Cayman Islands", dial_code: "+ 345", code: "KY"},
  {id: "41", title: "Central African Republic", dial_code: "+236", code: "CF"},
  {id: "42", title: "Chad", dial_code: "+235", code: "TD"},
  {id: "43", title: "Chile", dial_code: "+56", code: "CL"},
  {id: "44", title: "China", dial_code: "+86", code: "CN"},
  {id: "45", title: "Christmas Island", dial_code: "+61", code: "CX"},
  {id: "46", title: "Cocos (Keeling) Islands", dial_code: "+61", code: "CC"},
  {id: "47", title: "Colombia", dial_code: "+57", code: "CO"},
  {id: "48", title: "Comoros", dial_code: "+269", code: "KM"},
  {id: "49", title: "Congo", dial_code: "+242", code: "CG"},
  {id: "50", title: "Congo, The Democratic Republic of the Congo", dial_code: "+243", code: "CD"},
  {id: "51", title: "Cook Islands", dial_code: "+682", code: "CK"},
  {id: "52", title: "Costa Rica", dial_code: "+506", code: "CR"},
  {id: "53", title: "Cote d'Ivoire", dial_code: "+225", code: "CI"},
  {id: "54", title: "Croatia", dial_code: "+385", code: "HR"},
  {id: "55", title: "Cuba", dial_code: "+53", code: "CU"},
  {id: "56", title: "Cyprus", dial_code: "+357", code: "CY"},
  {id: "57", title: "Czech Republic", dial_code: "+420", code: "CZ"},
  {id: "58", title: "Denmark", dial_code: "+45", code: "DK"},
  {id: "59", title: "Djibouti", dial_code: "+253", code: "DJ"},
  {id: "60", title: "Dominica", dial_code: "+1767", code: "DM"},
  {id: "61", title: "Dominican Republic", dial_code: "+1849", code: "DO"},
  {id: "62", title: "Ecuador", dial_code: "+593", code: "EC"},
  {id: "63", title: "Egypt", dial_code: "+20", code: "EG"},
  {id: "64", title: "El Salvador", dial_code: "+503", code: "SV"},
  {id: "65", title: "Equatorial Guinea", dial_code: "+240", code: "GQ"},
  {id: "66", title: "Eritrea", dial_code: "+291", code: "ER"},
  {id: "67", title: "Estonia", dial_code: "+372", code: "EE"},
  {id: "68", title: "Ethiopia", dial_code: "+251", code: "ET"},
  {id: "69", title: "Falkland Islands (Malvinas)", dial_code: "+500", code: "FK"},
  {id: "70", title: "Faroe Islands", dial_code: "+298", code: "FO"},
  {id: "71", title: "Fiji", dial_code: "+679", code: "FJ"},
  {id: "72", title: "Finland", dial_code: "+358", code: "FI"},
  {id: "73", title: "France", dial_code: "+33", code: "FR"},
  {id: "74", title: "French Guiana", dial_code: "+594", code: "GF"},
  {id: "75", title: "French Polynesia", dial_code: "+689", code: "PF"},
  {id: "76", title: "Gabon", dial_code: "+241", code: "GA"},
  {id: "77", title: "Gambia", dial_code: "+220", code: "GM"},
  {id: "78", title: "Georgia", dial_code: "+995", code: "GE"},
  {id: "79", title: "Germany", dial_code: "+49", code: "DE"},
  {id: "80", title: "Ghana", dial_code: "+233", code: "GH"},
  {id: "81", title: "Gibraltar", dial_code: "+350", code: "GI"},
  {id: "82", title: "Greece", dial_code: "+30", code: "GR"},
  {id: "83", title: "Greenland", dial_code: "+299", code: "GL"},
  {id: "84", title: "Grenada", dial_code: "+1473", code: "GD"},
  {id: "85", title: "Guadeloupe", dial_code: "+590", code: "GP"},
  {id: "86", title: "Guam", dial_code: "+1671", code: "GU"},
  {id: "87", title: "Guatemala", dial_code: "+502", code: "GT"},
  {id: "88", title: "Guernsey", dial_code: "+44", code: "GG"},
  {id: "89", title: "Guinea", dial_code: "+224", code: "GN"},
  {id: "90", title: "Guinea-Bissau", dial_code: "+245", code: "GW"},
  {id: "91", title: "Guyana", dial_code: "+595", code: "GY"},
  {id: "92", title: "Haiti", dial_code: "+509", code: "HT"},
  {id: "93", title: "Holy See (Vatican City State)", dial_code: "+379", code: "VA"},
  {id: "94", title: "Honduras", dial_code: "+504", code: "HN"},
  {id: "95", title: "Hong Kong", dial_code: "+852", code: "HK"},
  {id: "96", title: "Hungary", dial_code: "+36", code: "HU"},
  {id: "97", title: "Iceland", dial_code: "+354", code: "IS"},
  {id: "98", title: "India", dial_code: "+91", code: "IN"},
  {id: "99", title: "Indonesia", dial_code: "+62", code: "ID"},
  {id: "100", title: "Iran, Islamic Republic of Persian Gulf", dial_code: "+98", code: "IR"},
  {id: "101", title: "Iraq", dial_code: "+964", code: "IQ"},
  {id: "102", title: "Ireland", dial_code: "+353", code: "IE"},
  {id: "103", title: "Isle of Man", dial_code: "+44", code: "IM"},
  {id: "104", title: "Israel", dial_code: "+972", code: "IL"},
  {id: "105", title: "Italy", dial_code: "+39", code: "IT"},
  {id: "106", title: "Jamaica", dial_code: "+1876", code: "JM"},
  {id: "107", title: "Japan", dial_code: "+81", code: "JP"},
  {id: "108", title: "Jersey", dial_code: "+44", code: "JE"},
  {id: "109", title: "Jordan", dial_code: "+962", code: "JO"},
  {id: "110", title: "Kazakhstan", dial_code: "+77", code: "KZ"},
  {id: "111", title: "Kenya", dial_code: "+254", code: "KE"},
  {id: "112", title: "Kiribati", dial_code: "+686", code: "KI"},
  {id: "113", title: "Korea, Democratic People's Republic of Korea", dial_code: "+850", code: "KP"},
  {id: "114", title: "Korea, Republic of South Korea", dial_code: "+82", code: "KR"},
  {id: "115", title: "Kuwait", dial_code: "+965", code: "KW"},
  {id: "116", title: "Kyrgyzstan", dial_code: "+996", code: "KG"},
  {id: "117", title: "Laos", dial_code: "+856", code: "LA"},
  {id: "118", title: "Latvia", dial_code: "+371", code: "LV"},
  {id: "119", title: "Lebanon", dial_code: "+961", code: "LB"},
  {id: "120", title: "Lesotho", dial_code: "+266", code: "LS"},
  {id: "121", title: "Liberia", dial_code: "+231", code: "LR"},
  {id: "122", title: "Libyan Arab Jamahiriya", dial_code: "+218", code: "LY"},
  {id: "123", title: "Liechtenstein", dial_code: "+423", code: "LI"},
  {id: "124", title: "Lithuania", dial_code: "+370", code: "LT"},
  {id: "125", title: "Luxembourg", dial_code: "+352", code: "LU"},
  {id: "126", title: "Macao", dial_code: "+853", code: "MO"},
  {id: "127", title: "Macedonia", dial_code: "+389", code: "MK"},
  {id: "128", title: "Madagascar", dial_code: "+261", code: "MG"},
  {id: "129", title: "Malawi", dial_code: "+265", code: "MW"},
  {id: "130", title: "Malaysia", dial_code: "+60", code: "MY"},
  {id: "131", title: "Maldives", dial_code: "+960", code: "MV"},
  {id: "132", title: "Mali", dial_code: "+223", code: "ML"},
  {id: "133", title: "Malta", dial_code: "+356", code: "MT"},
  {id: "134", title: "Marshall Islands", dial_code: "+692", code: "MH"},
  {id: "135", title: "Martinique", dial_code: "+596", code: "MQ"},
  {id: "136", title: "Mauritania", dial_code: "+222", code: "MR"},
  {id: "137", title: "Mauritius", dial_code: "+230", code: "MU"},
  {id: "138", title: "Mayotte", dial_code: "+262", code: "YT"},
  {id: "139", title: "Mexico", dial_code: "+52", code: "MX"},
  {id: "140", title: "Micronesia, Federated States of Micronesia", dial_code: "+691", code: "FM"},
  {id: "141", title: "Moldova", dial_code: "+373", code: "MD"},
  {id: "142", title: "Monaco", dial_code: "+377", code: "MC"},
  {id: "143", title: "Mongolia", dial_code: "+976", code: "MN"},
  {id: "144", title: "Montenegro", dial_code: "+382", code: "ME"},
  {id: "145", title: "Montserrat", dial_code: "+1664", code: "MS"},
  {id: "146", title: "Morocco", dial_code: "+212", code: "MA"},
  {id: "147", title: "Mozambique", dial_code: "+258", code: "MZ"},
  {id: "148", title: "Myanmar", dial_code: "+95", code: "MM"},
  {id: "149", title: "Namibia", dial_code: "+264", code: "NA"},
  {id: "150", title: "Nauru", dial_code: "+674", code: "NR"},
  {id: "151", title: "Nepal", dial_code: "+977", code: "NP"},
  {id: "152", title: "Netherlands", dial_code: "+31", code: "NL"},
  {id: "153", title: "Netherlands Antilles", dial_code: "+599", code: "AN"},
  {id: "154", title: "New Caledonia", dial_code: "+687", code: "NC"},
  {id: "155", title: "New Zealand", dial_code: "+64", code: "NZ"},
  {id: "156", title: "Nicaragua", dial_code: "+505", code: "NI"},
  {id: "157", title: "Niger", dial_code: "+227", code: "NE"},
  {id: "158", title: "Nigeria", dial_code: "+234", code: "NG"},
  {id: "159", title: "Niue", dial_code: "+683", code: "NU"},
  {id: "160", title: "Norfolk Island", dial_code: "+672", code: "NF"},
  {id: "161", title: "Northern Mariana Islands", dial_code: "+1670", code: "MP"},
  {id: "162", title: "Norway", dial_code: "+47", code: "NO"},
  {id: "163", title: "Oman", dial_code: "+968", code: "OM"},
  {id: "164", title: "Pakistan", dial_code: "+92", code: "PK"},
  {id: "165", title: "Palau", dial_code: "+680", code: "PW"},
  {id: "166", title: "Palestinian Territory, Occupied", dial_code: "+970", code: "PS"},
  {id: "167", title: "Panama", dial_code: "+507", code: "PA"},
  {id: "168", title: "Papua New Guinea", dial_code: "+675", code: "PG"},
  {id: "169", title: "Paraguay", dial_code: "+595", code: "PY"},
  {id: "170", title: "Peru", dial_code: "+51", code: "PE"},
  {id: "171", title: "Philippines", dial_code: "+63", code: "PH"},
  {id: "172", title: "Pitcairn", dial_code: "+872", code: "PN"},
  {id: "173", title: "Poland", dial_code: "+48", code: "PL"},
  {id: "174", title: "Portugal", dial_code: "+351", code: "PT"},
  {id: "175", title: "Puerto Rico", dial_code: "+1939", code: "PR"},
  {id: "176", title: "Qatar", dial_code: "+974", code: "QA"},
  {id: "177", title: "Romania", dial_code: "+40", code: "RO"},
  {id: "178", title: "Russia", dial_code: "+7", code: "RU"},
  {id: "179", title: "Rwanda", dial_code: "+250", code: "RW"},
  {id: "180", title: "Reunion", dial_code: "+262", code: "RE"},
  {id: "181", title: "Saint Barthelemy", dial_code: "+590", code: "BL"},
  {id: "182", title: "Saint Helena, Ascension and Tristan Da Cunha", dial_code: "+290", code: "SH"},
  {id: "183", title: "Saint Kitts and Nevis", dial_code: "+1869", code: "KN"},
  {id: "184", title: "Saint Lucia", dial_code: "+1758", code: "LC"},
  {id: "185", title: "Saint Martin", dial_code: "+590", code: "MF"},
  {id: "186", title: "Saint Pierre and Miquelon", dial_code: "+508", code: "PM"},
  {id: "187", title: "Saint Vincent and the Grenadines", dial_code: "+1784", code: "VC"},
  {id: "188", title: "Samoa", dial_code: "+685", code: "WS"},
  {id: "189", title: "San Marino", dial_code: "+378", code: "SM"},
  {id: "190", title: "Sao Tome and Principe", dial_code: "+239", code: "ST"},
  {id: "191", title: "Saudi Arabia", dial_code: "+966", code: "SA"},
  {id: "192", title: "Senegal", dial_code: "+221", code: "SN"},
  {id: "193", title: "Serbia", dial_code: "+381", code: "RS"},
  {id: "194", title: "Seychelles", dial_code: "+248", code: "SC"},
  {id: "195", title: "Sierra Leone", dial_code: "+232", code: "SL"},
  {id: "196", title: "Singapore", dial_code: "+65", code: "SG"},
  {id: "197", title: "Slovakia", dial_code: "+421", code: "SK"},
  {id: "198", title: "Slovenia", dial_code: "+386", code: "SI"},
  {id: "199", title: "Solomon Islands", dial_code: "+677", code: "SB"},
  {id: "200", title: "Somalia", dial_code: "+252", code: "SO"},
  {id: "201", title: "South Africa", dial_code: "+27", code: "ZA"},
  {id: "202", title: "South Sudan", dial_code: "+211", code: "SS"},
  {id: "203", title: "South Georgia and the South Sandwich Islands", dial_code: "+500", code: "GS"},
  {id: "204", title: "Spain", dial_code: "+34", code: "ES"},
  {id: "205", title: "Sri Lanka", dial_code: "+94", code: "LK"},
  {id: "206", title: "Sudan", dial_code: "+249", code: "SD"},
  {id: "207", title: "Suriname", dial_code: "+597", code: "SR"},
  {id: "208", title: "Svalbard and Jan Mayen", dial_code: "+47", code: "SJ"},
  {id: "209", title: "Swaziland", dial_code: "+268", code: "SZ"},
  {id: "210", title: "Sweden", dial_code: "+46", code: "SE"},
  {id: "211", title: "Switzerland", dial_code: "+41", code: "CH"},
  {id: "212", title: "Syrian Arab Republic", dial_code: "+963", code: "SY"},
  {id: "213", title: "Taiwan", dial_code: "+886", code: "TW"},
  {id: "214", title: "Tajikistan", dial_code: "+992", code: "TJ"},
  {id: "215", title: "Tanzania, United Republic of Tanzania", dial_code: "+255", code: "TZ"},
  {id: "216", title: "Thailand", dial_code: "+66", code: "TH"},
  {id: "217", title: "Timor-Leste", dial_code: "+670", code: "TL"},
  {id: "218", title: "Togo", dial_code: "+228", code: "TG"},
  {id: "219", title: "Tokelau", dial_code: "+690", code: "TK"},
  {id: "220", title: "Tonga", dial_code: "+676", code: "TO"},
  {id: "221", title: "Trinidad and Tobago", dial_code: "+1868", code: "TT"},
  {id: "222", title: "Tunisia", dial_code: "+216", code: "TN"},
  {id: "223", title: "Turkey", dial_code: "+90", code: "TR"},
  {id: "224", title: "Turkmenistan", dial_code: "+993", code: "TM"},
  {id: "225", title: "Turks and Caicos Islands", dial_code: "+1649", code: "TC"},
  {id: "226", title: "Tuvalu", dial_code: "+688", code: "TV"},
  {id: "227", title: "Uganda", dial_code: "+256", code: "UG"},
  {id: "228", title: "Ukraine", dial_code: "+380", code: "UA"},
  {id: "229", title: "United Arab Emirates", dial_code: "+971", code: "AE"},
  {id: "230", title: "United Kingdom", dial_code: "+44", code: "GB"},
  {id: "231", title: "United States", dial_code: "+1", code: "US"},
  {id: "232", title: "Uruguay", dial_code: "+598", code: "UY"},
  {id: "233", title: "Uzbekistan", dial_code: "+998", code: "UZ"},
  {id: "234", title: "Vanuatu", dial_code: "+678", code: "VU"},
  {id: "235", title: "Venezuela, Bolivarian Republic of Venezuela", dial_code: "+58", code: "VE"},
  {id: "236", title: "Vietnam", dial_code: "+84", code: "VN"},
  {id: "237", title: "Virgin Islands, British", dial_code: "+1284", code: "VG"},
  {id: "238", title: "Virgin Islands, U.S.", dial_code: "+1340", code: "VI"},
  {id: "239", title: "Wallis and Futuna", dial_code: "+681", code: "WF"},
  {id: "240", title: "Yemen", dial_code: "+967", code: "YE"},
  {id: "241", title: "Zambia", dial_code: "+260", code: "ZM"},
  {id: "242", title: "Zimbabwe", dial_code: "+263", code: "ZW"},
]

export {
  toolbarMenuItemsHome,
  searchBarMenuItemsHome,
  searchbarMenuItemsContacts,
  countryCodesMenuItems
};
